// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTeLSLq_f8Px463W6r_meogXo_Us8YQdA',
    appId: '1:278164667268:web:d954949fb20157c81dfbd1',
    messagingSenderId: '278164667268',
    projectId: 'currency-707b1',
    authDomain: 'currency-707b1.firebaseapp.com',
    storageBucket: 'currency-707b1.firebasestorage.app',
    measurementId: 'G-R2VW2M5HCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARS2QJDCEHc-G0bDk0UdY9cm3Eht0MFAs',
    appId: '1:278164667268:android:9ca7501de9300a771dfbd1',
    messagingSenderId: '278164667268',
    projectId: 'currency-707b1',
    storageBucket: 'currency-707b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkWF2ZX3TNBaUYjdl1gr42S5CnWzcm_r4',
    appId: '1:278164667268:ios:6eea17ec4d6949c51dfbd1',
    messagingSenderId: '278164667268',
    projectId: 'currency-707b1',
    storageBucket: 'currency-707b1.firebasestorage.app',
    iosBundleId: 'com.example.currencyConversion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkWF2ZX3TNBaUYjdl1gr42S5CnWzcm_r4',
    appId: '1:278164667268:ios:6eea17ec4d6949c51dfbd1',
    messagingSenderId: '278164667268',
    projectId: 'currency-707b1',
    storageBucket: 'currency-707b1.firebasestorage.app',
    iosBundleId: 'com.example.currencyConversion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTeLSLq_f8Px463W6r_meogXo_Us8YQdA',
    appId: '1:278164667268:web:2f71778489c8b9621dfbd1',
    messagingSenderId: '278164667268',
    projectId: 'currency-707b1',
    authDomain: 'currency-707b1.firebaseapp.com',
    storageBucket: 'currency-707b1.firebasestorage.app',
    measurementId: 'G-Z48XCVJB3K',
  );

  static late DefaultFirebaseOptions instance;

  Future<void> sendPasswordResetEmail({required String email}) async {}
}
